# Generated by Django 4.2.7 on 2025-09-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0002_alter_company_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='COMP', help_text='Short company code (e.g., ACME)', max_length=10),
        ),
    ]
