# Generated by Django 4.2.7 on 2025-09-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0006_add_biometricdevice_comm_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='annual_leave_days',
        ),
        migrations.RemoveField(
            model_name='company',
            name='code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='notice_period_days',
        ),
        migrations.RemoveField(
            model_name='company',
            name='probation_period_months',
        ),
        migrations.RemoveField(
            model_name='company',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sick_leave_days',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='work_end_time',
        ),
        migrations.RemoveField(
            model_name='company',
            name='work_start_time',
        ),
        migrations.RemoveField(
            model_name='company',
            name='working_days_per_week',
        ),
        migrations.AddField(
            model_name='company',
            name='max_employees',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(default='basic', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core_hr.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core_hr.company'),
            preserve_default=False,
        ),
    ]
