# Generated by Django 4.2.7 on 2025-09-18 16:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_hr', '0007_remove_company_annual_leave_days_remove_company_code_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('salary_created', 'Salary Created'), ('salary_updated', 'Salary Updated'), ('salary_approved', 'Salary Approved'), ('salary_rejected', 'Salary Rejected'), ('payroll_generated', 'Payroll Generated'), ('payslip_created', 'Payslip Created'), ('payslip_updated', 'Payslip Updated'), ('employee_created', 'Employee Created'), ('employee_updated', 'Employee Updated')], max_length=30)),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.PositiveIntegerField()),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PayrollGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('generation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('total_employees', models.PositiveIntegerField(default=0)),
                ('payslips_generated', models.PositiveIntegerField(default=0)),
                ('total_gross_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('errors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-generation_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.JSONField(blank=True, default=dict)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this salary change')),
            ],
            options={
                'verbose_name_plural': 'Salary History Records',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='employeesalary',
            new_name='payroll_emp_is_acti_3e9f8c_idx',
            old_name='payroll_empl_is_acti_ef1b48_idx',
        ),
        migrations.RenameIndex(
            model_name='payslip',
            new_name='payroll_pay_employe_1b0b6b_idx',
            old_name='payroll_pays_employ_6b9c88_idx',
        ),
        migrations.RenameIndex(
            model_name='taxbracket',
            new_name='payroll_tax_is_acti_e24906_idx',
            old_name='payroll_taxb_is_acti_1a415a_idx',
        ),
        migrations.AddField(
            model_name='payslip',
            name='allowances_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payslip',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='days_absent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='days_worked',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='payslip',
            name='deductions_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payslip',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved'), ('paid', 'Paid')], default='generated', max_length=20),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tax_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_allowances',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='working_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='core_hr.employee'),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_salary_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollgeneration',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_generations', to='core_hr.company'),
        ),
        migrations.AddField(
            model_name='payrollgeneration',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core_hr.company'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payrollgeneration'),
        ),
        migrations.AddIndex(
            model_name='salaryhistory',
            index=models.Index(fields=['employee', 'status', 'effective_date'], name='payroll_sal_employe_dfe83e_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryhistory',
            index=models.Index(fields=['status', 'effective_date'], name='payroll_sal_status_a3c6c4_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollgeneration',
            index=models.Index(fields=['company', 'pay_period_end'], name='payroll_pay_company_77da2c_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollgeneration',
            index=models.Index(fields=['status', 'generation_date'], name='payroll_pay_status_48630d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollgeneration',
            unique_together={('company', 'pay_period_start', 'pay_period_end')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'timestamp'], name='payroll_aud_company_77494c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='payroll_aud_user_id_0d6ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='payroll_aud_action__75b382_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='payroll_aud_target__0e3ab3_idx'),
        ),
    ]
