# Generated by Django 4.2.7 on 2025-09-19 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0002_auditlog_payrollgeneration_salaryhistory_and_more'),
    ]

    operations = [
        # Add new fields to EmployeeSalary
        migrations.AddField(
            model_name='employeesalary',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                default='approved',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='approved_salaries',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # Update EmployeeSalary fields
        migrations.AlterField(
            model_name='employeesalary',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='employee',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='salaries',
                to='core_hr.employee'
            ),
        ),

        # Add index for better performance
        migrations.AddIndex(
            model_name='employeesalary',
            index=models.Index(
                fields=['employee', 'is_active', 'status'],
                name='payroll_emp_salary_idx'
            ),
        ),
    ]
