# Generated by Django 4.2.7 on 2025-09-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_838e43_idx',
            old_name='notif_user_read_idx',
        ),
    ]
