# Generated by Django 4.2.7 on 2025-09-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0002_alter_company_options_alter_department_options_and_more'),
        ('accounts', '0002_user_company_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core_hr.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('hr_manager', 'HR Manager'), ('super_admin', 'Super Administrator')], default='employee', help_text='User role determines access permissions', max_length=20),
        ),
    ]
